# WHAT IS BROADCASTING ?
#-> IN DATA HAVE A MANY TYPES OF ARRAY ANE LISTS SO,
# IF YOU PERFORM SOME TASK WHOLE ARRAY AT ONCE TYPE THAN WE USE BROADCASTING.

# IF YOU PERFORM A SOME TASK IN WHOOL DATA ,
# SO IN LIST YOU WILL CREATE LIST AND AFTER FOR LOOP YOU ACCESS ALL ELEMENTS AND PERFORM SOME TASK.
# BUT IF YOU CREATE ARRAY YOU CAN EASILY PERFORM OPERATION AT SINGLE TIME WITHOUT USING LOOP.

# EXAMPLE
import numpy as np

array = np.array([100 , 250 , 500])

discount = 10

final_price = array - (array * discount / 100)

print(final_price)
