# THERE ARE 3 TYPES OF BROADCASTING
# 1-> MAGIC DIMENSION :-
    # IF MULTIPLE ARRAY SIZE ARE SAME THAN NUMPY HAS EASILY PERFORM SOME TASK AND OPERATION

# EXAMPLE :-

import numpy as np

array_1 = np.array([10,20,30])
array_2 = np.array([40,50,60])

print((array_1 + array_2))

# 2-> EXPANDING SINGLE ELEMENTS :-
    # IF ARRAY SIZE ARE DIFFERENT LIKE ONE ARRAY HAV BIG AND ANOTHER HAV SMALL ,
    # SO A SMALL ARRAY CAN AUTOMATICALLY EXPEND LIKE A FIRST ARRAY SIZE

#  EXAMPLE :-

array_3 = np.array([10,20,30])
array_4 = np.array([40])

print(array_3 + array_4)

# LOOK THIS EXAMPLE 40 HAVE EXPENDED AND ADDITION BY 10 , 20 , 30

# 3-> INCOMPARABLE SHAPE :-
    # IF ARRAYS ELEMENTS ARE OUT OF RANGE BY OTHER ARRAY ELEMENTS SO NUMPY GIVES YOU VALUE ERRORS.

# EXAMPLE :-

array_5 = np.array([10.,20,30])
array_6 = np.array([40,50])

print(array_5 + array_6)