#1-> WHY WE USE ?
# -> IN REAL WORLD DATA HAVE A MANY MISSING VALUES AND NONE VALUES ,
# IF YOU BECOME A GOOD DATA SCIENTIST SO YOU ALSO DEAL WITH LARGE DATA,
# AND A DATA HAD A NOT A STRUCTURE FORM SO YOU ALSO DEAL WITH NUN AND UNSTRUCTURED DATA THAN WE USE MISSING VALUES

# THERE ARE 3 BUILT-IN FUNCTION IN NUMPY
#1-> ISNAN() -> IF USING DATA HAVE MISSING VALUES
#2-> NAN() -> IF YOU REPLACE NUN VALUES INTO OTHER VALUES
#3-> ISINF() -> DETRACT INFINITE FUNCTION




