# WHAT IS INDEXING ?
# -> IF YOU ARE GETTING SINGLE ELEMENTS IN LARGE AND MULTIPLE NUMBERS IN ARRAY SO YOU USE A INDEXING.
# -> USING INDEXING YOU CAN PICK A SINGLE ELEMENT IN ARRAY.
#SYNTAX:- a[index]
#-> IF T=YOU WORKING WITH 2D ARRAY SO YOU CAN USE ROW AND COLUM FOR INDEXING.


# WHAT IS SLICING ?
#-> IF YOU CAN PICK MULTIPLE VALUES IN SINGLE ARRAY SO USE SLICING,
#-> USING SLICING YOU PICK MULTIPLE VALUES , ALSO DEFINE  START AND STOP TO PERFORM SLICING
#SYNTAX:- a[startindex:endindex:increment]


# FANCY INDEXING ?
#-> MULTIPLE ELEMENTS ARE CHOOSING BY ONCE USING LIST

# BOOLEAN MASTERY ?
#->  IF YOU NEED A RESULT OF YOUR CONDITION SO USING THIS .


# NOTE :- NUMPY WORKING WITH ZERO BASE INDEXING COUNT STRAT WITH ZERO